export const TEACHER_SALARY_REQUEST = 'TEACHER_SALARY_REQUEST'
export const TEACHER_SALARY_SUCCESS = 'TEACHER_SALARY_SUCCESS'
export const TEACHER_SALARY_FAIL = 'TEACHER_SALARY_FAIL'
export const TEACHER_SALARY_RESET = 'TEACHER_SALARY_RESET'

export const TEACHER_REGISTER_REQUEST = 'TEACHER_REGISTER_REQUEST'
export const TEACHER_REGISTER_SUCCESS = 'TEACHER_REGISTER_SUCCESS'
export const TEACHER_REGISTER_FAIL = 'TEACHER_REGISTER_FAIL'
export const TEACHER_REGISTER_RESET = 'TEACHER_REGISTER_RESET'


export const TEACHER_DELETE_REQUEST = 'TEACHER_DELETE_REQUEST'
export const TEACHER_DELETE_SUCCESS = 'TEACHER_DELETE_SUCCESS'
export const TEACHER_DELETE_FAIL = 'TEACHER_DELETE_FAIL'
export const TEACHER_DELETE_RESET = 'TEACHER_DELETE_RESET'




export const TEACHER_LIST_REQUEST = 'TEACHER_LIST_REQUEST'
export const TEACHER_LIST_SUCCESS = 'TEACHER_LIST_SUCCESS'
export const TEACHER_LIST_FAIL = 'TEACHER_LIST_FAIL'
export const TEACHER_LIST_RESET = 'TEACHER_LIST_RESET'


