export const TEACHER_SALARY_REQUEST = 'TEACHER_SALARY_REQUEST'
export const TEACHER_SALARY_SUCCESS = 'TEACHER_SALARY_SUCCESS'
export const TEACHER_SALARY_FAIL = 'TEACHER_SALARY_FAIL'
export const TEACHER_SALARY_RESET = 'TEACHER_SALARY_RESET'

export const TEACHER_REGISTER_REQUEST = 'TEACHER_REGISTER_REQUEST'
export const TEACHER_REGISTER_SUCCESS = 'TEACHER_REGISTER_SUCCESS'
export const TEACHER_REGISTER_FAIL = 'TEACHER_REGISTER_FAIL'
export const TEACHER_REGISTER_RESET = 'TEACHER_REGISTER_RESET'